### ISSUE TITLE
Bug: Does not work for VIM

### ISSUE THREAD

**Issue by mikeczech** [christophstockhusen/bigquery-mode#1]
I have copied the bigquery-mode.el and bqm-names.el to my load path, bit still cannot use the bq-mode in VIM.

Please fix that. Thanks!

**Comment by christophstockhusen** [comment]
Strange. Please try to update your Vim to Emacs 26.3. Does this resolve the issue?

**Comment by mikeczech** [comment]
Thank you very much!
